### ISSUE TITLE
Is redream maintained?

### ISSUE THREAD

**Issue by dariusc93** [libretro/redream#1]
I would like to know if redream is going to be maintained by libretro team? I already know about what inolen did (making redream closed source, despite the licensing, and having people pay for binary form of the emulator), but considering how many forks there are, its hard to say who will maintain what, or who to report bugs too.

**Comment by RobLoach** [comment]
https://github.com/libretro/RetroArch/issues/6066

**Comment by fr500** [comment]
I'd just keep the repo and remove all builds/disable buildbot since those are useless at the time being.
If it's even open sourced again it could be revisited.
