### ISSUE TITLE
M3U playlist not working

### ISSUE THREAD

**Issue by DJoneK** [libretro/redream#2]
If I try to load a multi-disc playlist (.m3u) using CHDs, it fails to load.  It freezes on a black screen.  The boot logo never shows up.

Enabling Logging Verbose and using the debug exe, I noticed it stopped here:

> [INFO] [GL]: VSync => on
> [INFO] [WGL]: wglSwapInterval(1)
> [WARN] [WGL]: wglSwapInterval() failed.
> [INFO] Paused.

CHDs load just fine independently.

**Comment by Hedonium** [comment]
Pretty sure this core doesn't support m3u at all.

It's not listed as a valid extension here. https://github.com/libretro/redream/blob/master/src/host/retro_host.c#L217

**Comment by DJoneK** [comment]
Ah, forgot to check for that.  You are correct.  Took it for granted that m3u should work on cores with multi-discs. :/
